---
title: Jocelyn Lee
timezone: UTC
collections:
  navigation:
    title: Navigation
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
- scope:
    path: contact-success.html
  values:
    layout: page
baseurl: 
google_analytics_key: UA-84803515-1
google_maps_javascript_api_key: 
logo: "/siteicon.png"
description: 'This is an authentic source of deep living and loving. Jocelyn documents
  and shares her spiritual life journey and provides a deeper perspective on life
  through social commentary.  '
aboutMe: "I am a star-shaped person breaking out of a box-shaped world. My journey
  of becoming and being myself is a deep and spiritual one. I love sharing my brightest
  of days and my darkest of nights, with the intention to be an example of a deep
  way of living. \n\nBecause I am infinitely curious and full of sincere enthusiasm
  for all aspects of life, I share my unique perspective through social commentary.
  My intention is to bring the light of awareness, compassion, depth, and acceptance
  into all spaces of life."
author:
  name: Jocelyn Lee
  email: jocelyn@jocelynlee.ca
  twitter: 
social:
  name: Jocelyn Lee
  links:
  - http://jocelynlee.ca
  - http://elevatesex.com
  - http://julianjorgensen.com
disqus_shortname: jocelynlee
permalink: "/blog/:title/"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-archives
include:
- _redirects
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
paginate: 10
paginate_path: "/blog/:num/"
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Instagram
- YouTube
- Email
_comments:
  description: 'An authentic source of deep living and loving. Jocelyn documents and
    shares her spiritual life journey and provides a deeper perspective on life through
    social commentary.  '
  blurb: A deeper look into the human condition.
