# Site Settings
baseurl: 		""
title: 			Jocelyn Lee

name: 			Jocelyn Lee
description: 	Jocelyn Lee blog

gems: [jekyll-paginate]

paginate: 3
paginate_path: 	"blog/page:num"

twitter: 		jocelynleeblog
email: 			koichihealing@gmail.com

disqus: 		jocelynleeblog
analytics: 		UA-84803515-1

copyright: 		Copyright Jocelyn Lee 2016

# Build Settings
permalinks: 	pretty


# Collections
collections:
  tags:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "tags"
    values:
      layout: "default"
