---
title: Jocelyn Lee
timezone: UTC
collections:
  navigation:
    title: Navigation
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
- scope:
    path: contact-success.html
  values:
    layout: page
baseurl: 
google_analytics_key: UA-84803515-1
google_maps_javascript_api_key: 
logo: "/siteicon.png"
description: Spirituality, Sexuality, and Artistry with Jocelyn Lee
aboutMe: I am a woman of many faces and many places, a star-shaped human in a box-shaped
  world. Being human is the most beautiful and challenging journey, and there is only
  my unique individual way of living it. I, LIVE.DEEP.LEE.
author:
  name: Jocelyn Lee
  email: jocelyn@jocelynlee.ca
  twitter: 
social:
  name: Jocelyn Lee
  links:
  - http://jocelynlee.ca
  - http://elevatesex.com
  - http://julianjorgensen.com
disqus_shortname: jocelynlee
permalink: "/blog/:title/"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-archives
include:
- _redirects
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
paginate: 10
paginate_path: "/blog/:num/"
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Instagram
- YouTube
- Email
_comments:
  description: 'LIVE DEEP LEE with Jocelyn as she shares her deep perspectives on
    life and her personal spiritual journey. This is an authentic source of deep living
    and loving. '
  blurb: 
