---
title: Jocelyn Lee
timezone: UTC
collections:
  navigation:
    title: Navigation
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
- scope:
    path: contact-success.html
  values:
    layout: page
baseurl: 
google_analytics_key: UA-84803515-1
google_maps_javascript_api_key: 
logo: "/siteicon.png"
description: Spirituality, Sexuality, and Artistry with Jocelyn Lee
aboutMe: I invite you to join me as I traverse the mysterious metaphysical world as
  a Spirit Weaver to bridge you with the unknown. I reveal with you intimate details
  of living tantra as a Tantrika Goddess to awaken your heart. I share my creations
  as a Shapeshifting Artist to express my soul. I serve by coaching women into full
  bodied empowerment.
author:
  name: Jocelyn Lee
  email: jocelyn@jocelynlee.ca
  twitter: 
social:
  name: Jocelyn Lee
  links:
  - http://jocelynlee.ca
  - http://elevatesex.com
  - http://julianjorgensen.com
disqus_shortname: jocelynlee
permalink: "/blog/:title/"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-archives
include:
- _redirects
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
paginate: 10
paginate_path: "/blog/:num/"
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Instagram
- YouTube
- Email
_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
