# ----
# Site

title: Jocelyn Lee
url: "http://jocelynlee.ca"
baseurl:
google_analytics_key: UA-84803515-1
google_maps_javascript_api_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Spirituality, Sexuality, and Artistry with Jocelyn Lee
author:
  name: Jocelyn Lee
  email: jocelyn@jocelynlee.ca
  twitter: # twitter username without the @ symbol
social:
  name: Jocelyn Lee
  links:
    - http://jocelynlee.ca
    - http://elevatesex.com
    - http://julianjorgensen.com
disqus_shortname: jocelynlee

# -----
# Build

permalink: /blog/:categories/:title/

plugins:
  - EnvironmentVariablesGenerator

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - YouTube
  - Email

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
