---
title: Jocelyn Lee
timezone: UTC

name: Jocelyn Lee
description: A Tantric Journey
url: "http://localhost:4000"

gems: [jekyll-paginate]

paginate: 3
paginate_path: "blog/page:num"

twitter: jocelynleeblog
email: koichihealing@gmail.com

disqus: jocelynleeblog
analytics: 		UA-84803515-1

copyright: 		Copyright 2016 Jocelyn Lee

# Build Settings
permalinks: 	pretty

# Collections
collections:
  tags:
    output: true
    _hide_content: true

defaults:
  -
    scope:
      path: ""
      type: "tags"
    values:
      layout: "default"
