# Site Settings
baseurl: 		""
title: 			Jocelyn Lee

name: 			Jocelyn Lee
description: 	Jocelyn Lee blog

gems: [jekyll-paginate]

paginate: 3
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			koichihealing@gmail.com

disqus: 		your_disqus_shortname
analytics: 		UA-84803515-1

copyright: 		Copyright Jocelyn Lee 2016

# Build Settings
permalinks: 	pretty
