---
title: Jocelyn Lee
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image:
- scope:
    path: contact-success.html
  values:
    layout: page
baseurl:
google_analytics_key: UA-84803515-1
google_maps_javascript_api_key:
logo: "/siteicon.png"
description: Spirituality, Sexuality, and Artistry with Jocelyn Lee
author:
  name: Jocelyn Lee
  email: jocelyn@jocelynlee.ca
  twitter:
social:
  name: Jocelyn Lee
  links:
  - http://jocelynlee.ca
  - http://elevatesex.com
  - http://julianjorgensen.com
disqus_shortname: jocelynlee
permalink: "/blog/:categories/:title/"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-archives
include:
- _redirects
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
paginate: 10
paginate_path: "/blog/:num/"
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Instagram
- YouTube
- Email
_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
