---
title: Jocelyn Lee
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tags:
    title: Tags
    output: true
    _hide_content: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: tags
  values:
    layout: default
baseurl: ''
name: Jocelyn Lee
description: Jocelyn Lee blog
gems:
- jekyll-paginate
paginate: 3
paginate_path: blog/page:num
twitter: jocelynleeblog
email: koichihealing@gmail.com
disqus: jocelynlee
analytics: UA-84803515-1
copyright: Copyright Jocelyn Lee 2016
permalinks: pretty
